### ISSUE TITLE
ApiException is not catchable

### ISSUE THREAD

**Issue by TiGR** [Giftd/giftd-php-client#4]
Due to error in namespaces. You use `PSR-0` autoloader, but exceptions do not follow the standard.

`ApiException` as well as `NetworkException` are located in `Giftd/Exceptions`, but their namespace is `Giftd`. So, once it is being used you end up with class not found exception.

**Comment by alexn-ops** [comment]
TiGR, thank you for the bug report again! :)

Fixed it, please check out the new version (1.1.3).

**Comment by TiGR** [comment]
You seem to have not enabled auto-update for packagist, it still sees only version 1.1.2.

**Comment by alexn-ops** [comment]
You're right, sorry, finally it's on the packagist.
